format="$all"
[character]
success_symbol="[âœ](#50c878)"
error_symbol = "[âœ–](bold red) "

[line_break]
disabled=true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[git_branch]
style="#50c878"
symbol = "ğŸŒ± "

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ â‡¡${count}"
behind = "ğŸ¢ â‡£${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = '[++\($count\)](green)'
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[conda]
format = "[$symbol$environment](#50c878)"

[python]
style="yellow bold"
format="[$symbol$version]($style)"

